### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by youngstu** [victorqin/motion_inbetweening#1]
```
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbce0993be0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/requests-2.27.1-py3.8.egg/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py38_pytorch1.9/lib/python3.8/site-packages/urllib3-1.26.9-py3.8.egg/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/Motion%20Inbetween%20-%20lafan1_context_model_release (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbce0993be0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:
```

**Comment by victorqin** [comment]
Are you training from scratch? Did you launch visdom before start training (see readme.md)?
